update book set author_id=1 where id=1;
update book set author_id=1 where id=2;
update book set author_id=1 where id=3;
update book set author_id=1 where id=4;
update book set author_id=2 where id=5;
update book set author_id=2 where id=6;
update book set author_id=2 where id=7;
update book set author_id=2 where id=8;
update book set author_id=2 where id=9;
